# Version de Kustomize
apiVersion: kustomize.config.k8s.io/v1beta1

# Type de configuration
kind: Kustomization

# Namespace appliqué automatiquement
namespace: techshop

# Liste complète des ressources Kubernetes
resources:
  - namespace.yaml
  - postgres-secret.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - user-deployment.yaml
  - user-service.yaml
  - product-deployment.yaml
  - product-service.yaml
  - order-deployment.yaml
  - order-service.yaml
  - api-gateway-deployment.yaml
  - api-gateway-service.yaml