#Version de l'API Kubernetes utilisée
apiVersion: v1
#Type de ressource
kind: Secret
metadata:
#Nom du secret
  name: postgres-secret
  #Namespace dans lequel sera créé le secret
  namespace: techshop
  #Type Opaque = secret générique (clé/valeur)
type: Opaque
#Les données doivent être encodées en base64
data:
#Nom de la base de données
  POSTGRES_DB: dGVjaHNob3A=
  #Nom d'utilisateur PostgreSQL
  POSTGRES_USER: dGVjaHNob3A=
  #Mot de passe PostgreSQL
  POSTGRES_PASSWORD: dGVjaHNob3A=